all:
  hosts:
    pi:
      ansible_connection: ssh
      ansible_host: pi
    hass:
      ansible_connection: ssh
      ansible_host: hass
    nas:
      ansible_connection: ssh
      ansible_host: ironforge
  vars:
    container_name: portainer
    container_name_agent: portainer_agent
    image_name_main: portainer/portainer-ce:latest
    image_name_agent: portainer/agent:latest
    nas_mount: -v /var/run/docker.sock:/var/run/docker.sock -v /volume2/@docker/volumes:/var/lib/docker/volumes
    hass_mount: -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes
    main_mount: -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data
    agent_port: -p 9001:9001
    main_ports: -p 8000:8000 -p 9000:9000 -p 9443:9443
    main_command: docker run -d
    nas_command: /usr/local/bin/docker